import fs from "fs";
import path from "path";
import { execSync } from "child_process";

const COMPILER_DIR = path.join(process.cwd(), "compiler_template");

/**
 * Compiles a custom Soroban smart contract (Rust) into WASM bytecode.
 * Overwrites src/lib.rs in the compiler workspace, triggers a cargo build,
 * and reads the generated .wasm file buffer.
 */
export function compileRustContract(rustCode: string): Buffer {
  console.log("[Compiler] Overwriting src/lib.rs with custom Rust code...");
  
  const libPath = path.join(COMPILER_DIR, "src/lib.rs");
  fs.writeFileSync(libPath, rustCode);

  console.log("[Compiler] Cleaning target directory to invalidate cache...");
  try {
    execSync("cargo clean", { cwd: COMPILER_DIR });
  } catch (error: any) {
    console.warn("[Compiler] Warning: cargo clean failed:", error.message);
  }

  console.log("[Compiler] Executing Cargo build target wasm32-unknown-unknown...");
  try {
    // Run cargo build synchronously. Disable reference-types and multi-value features which are unsupported by Soroban VM validator.
    execSync("cargo build --target wasm32-unknown-unknown --release", {
      cwd: COMPILER_DIR,
      stdio: "pipe", // keep logs in case we need to diagnose compile errors
      env: {
        ...process.env,
        RUSTFLAGS: "-C target-feature=-reference-types,-multi-value"
      }
    });
  } catch (error: any) {
    const errorMsg = error.stderr ? error.stderr.toString() : error.message;
    console.error("[Compiler] Cargo compilation error details:", errorMsg);
    throw new Error(`Rust Compilation Error:\n${errorMsg.slice(-400)}`);
  }

  // Find the compiled wasm file (Cargo replaces hyphens with underscores for the wasm target)
  const wasmPath = path.join(
    COMPILER_DIR,
    "target/wasm32-unknown-unknown/release/soroban_custom_compiler.wasm"
  );

  if (!fs.existsSync(wasmPath)) {
    throw new Error("WASM file was not generated by Cargo build.");
  }

  console.log("[Compiler] Smart contract built successfully!");
  return fs.readFileSync(wasmPath);
}
